preprocess:
  balancing: smoteenn       #smote -SMOTE 
                          # adasyn -ADASYN
                          #borderline_smote -BorderlineSMOTE
                          #random_oversample -RandomOverSampler
                          #smotetomek -SMOTETomek
                          #smoteenn -SMOTEENN
                          #random_undersample -RandomUnderSampler
                          #tomeklinks -TomekLinks

split:
  test_size: 0.2
  random_state: 42

train:
  algorithm: "SVM" # options: "LogisticRegression", "SVM", "RandomForest", "XGBoost"
  random_state: 42
  
 
  LogisticRegression:
    C: 1.0
    max_iter: 1000
    
  SVM:
    C: 1.0
    kernel: "rbf"
    probability: true
    
  RandomForest:
    n_estimators: 100
    max_depth: 10
    
  XGBoost:
    n_estimators: 150
    learning_rate: 0.05
    max_depth: 6
    eval_metric: "logloss"
    
    