stages:
  preprocess:
    cmd: python src/preprocess.py data/online_shoppers_intention.csv data/processed
    deps:
      - src/preprocess.py
      - data/online_shoppers_intention.csv
    outs:
      - data/processed/online_shoppers_intention_cleaned.csv
      - data/processed/metadata.json

  split:
    cmd: python src/split.py data/processed/online_shoppers_intention_cleaned.csv data/prepared
    deps:
      - src/split.py
      - data/processed/online_shoppers_intention_cleaned.csv
    params:
      - split.test_size
      - split.random_state
    outs:
      - data/prepared/train.csv
      - data/prepared/test.csv

  train:
    cmd: python src/train.py data/prepared/train.csv models/model.joblib
    deps:
      - src/train.py
      - data/prepared/train.csv
    params:
      - preprocess.balancing
      - train
    outs:
      - models/model.joblib

  evaluate:
    cmd: python src/evaluate.py models/model.joblib data/prepared/test.csv metrics/metrics.json
    deps:
      - src/evaluate.py
      - models/model.joblib
      - data/prepared/test.csv
    metrics:
      - metrics/metrics.json:
          cache: false