preprocess:
  balancing: smote

split:
  test_size: 0.2
  random_state: 42

train:
  algorithm: SVM
  random_state: 42

  LogisticRegression:
    max_iter: 1000
    class_weight: balanced

  SVM:
    C: 1.0
    kernel: rbf
    probability: true
    class_weight: balanced

  RandomForest:
    n_estimators: 200
    max_depth: 12
    class_weight: balanced

  XGBoost:
    n_estimators: 200
    max_depth: 5
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    
    